import type {Product} from "@/entities/products/model/type.ts";

export const products: Product[] = [
    {
        id: 1,
        name: 'Nike Air Max 270',
        type: 'Sneakers',
        price: 129,
        discount: 0.2,
        purchasedCount: 156,
    },
    {
        id: 2,
        name: 'Nike ZoomX Invincible',
        type: 'Sneakers',
        price: 179,
        discount: 0.15,
        purchasedCount: 243,
    },
    {
        id: 3,
        name: 'Adidas Ultraboost 5',
        type: 'Sneakers',
        price: 189,
        discount: 0.25,
        purchasedCount: 317,
    },
    {
        id: 4,
        name: 'Puma Velocity Nitro',
        type: 'Sneakers',
        price: 149,
        purchasedCount: 84,
    },
    {
        id: 5,
        name: 'New Balance 9060',
        type: 'Sneakers',
        price: 169,
        discount: 0.3,
        purchasedCount: 201,
    },
    {
        id: 6,
        name: 'Asics Gel-Kayano 31',
        type: 'Sneakers',
        price: 199,
        discount: 0.2,
        purchasedCount: 128,
    },
    {
        id: 7,
        name: 'Nike Pegasus 41',
        type: 'Sneakers',
        price: 139,
        discount: 0.15,
        purchasedCount: 412,
    },
    {
        id: 8,
        name: 'Adidas Adizero Boston',
        type: 'Sneakers',
        price: 159,
        purchasedCount: 178,
    },
    {
        id: 9,
        name: 'Reebok Floatride Energy',
        type: 'Sneakers',
        price: 119,
        discount: 0.25,
        purchasedCount: 92,
    },
    {
        id: 10,
        name: 'Under Armour HOVR Phantom',
        type: 'Sneakers',
        price: 149,
        discount: 0.2,
        purchasedCount: 135,
    },
    {
        id: 11,
        name: 'Saucony Endorphin Speed',
        type: 'Sneakers',
        price: 189,
        discount: 0.4,
        purchasedCount: 267,
    },
    {
        id: 12,
        name: 'Hoka Clifton 10',
        type: 'Sneakers',
        price: 174,
        purchasedCount: 351,
    },
];