import type {Product} from "@/entities/products/model/type.ts";

const computers: Product[] = [
    {
        id: 1,
        categoryId: 1,
        name: 'Quantum Core X1',
        type: 'Gaming PC',
        description: 'High-performance gaming system designed for modern AAA titles and competitive gaming. Delivers smooth performance, fast load times, and reliable cooling.',
        price: 1899,
        discount: 0.2,
        purchasedCount: 156,
        imgSrc: '/images/computers/1.png',
    },
    {
        id: 2,
        categoryId: 1,
        name: 'Nebula Storm Pro',
        type: 'Gaming PC',
        description: 'High-performance gaming system designed for modern AAA titles and competitive gaming. Delivers smooth performance, fast load times, and reliable cooling.',
        price: 2099,
        discount: 0.15,
        purchasedCount: 243,
        imgSrc: '/images/computers/2.png',
    },
    {
        id: 3,
        categoryId: 1,
        name: 'Aurora Fusion X',
        type: 'Gaming PC',
        description: 'High-performance gaming system designed for modern AAA titles and competitive gaming. Delivers smooth performance, fast load times, and reliable cooling.',
        price: 2299,
        discount: 0.25,
        purchasedCount: 317,
        imgSrc: '/images/computers/3.png',
    },
    {
        id: 4,
        categoryId: 1,
        name: 'Titan RGB Elite',
        type: 'Gaming PC',
        description: 'High-performance gaming system designed for modern AAA titles and competitive gaming. Delivers smooth performance, fast load times, and reliable cooling.',
        price: 2499,
        purchasedCount: 84,
        imgSrc: '/images/computers/4.png',
    },
    {
        id: 5,
        categoryId: 1,
        name: 'CyberForge Mini',
        type: 'Gaming PC',
        description: 'High-performance gaming system designed for modern AAA titles and competitive gaming. Delivers smooth performance, fast load times, and reliable cooling.',
        price: 1599,
        discount: 0.3,
        purchasedCount: 201,
        imgSrc: '/images/computers/5.png',
    },
    {
        id: 6,
        categoryId: 1,
        name: 'Infinity View One',
        type: 'All-in-One PC',
        description: 'Space-saving desktop solution with a sleek integrated design. Perfect for productivity, entertainment, and everyday use.',
        price: 1399,
        discount: 0.2,
        purchasedCount: 128,
        imgSrc: '/images/computers/6.png',
    },
    {
        id: 7,
        categoryId: 1,
        name: 'Crystal Edge Pro',
        type: 'Laptop',
        description: 'Portable and powerful laptop built for work, study, and daily multitasking. Offers excellent performance with long-lasting reliability.',
        price: 1499,
        discount: 0.2,
        purchasedCount: 135,
        imgSrc: '/images/computers/7.png',
    },
    {
        id: 8,
        categoryId: 1,
        name: 'Vortex Ultra X',
        type: 'Gaming Laptop',
        description: 'Powerful gaming laptop featuring high-end hardware for demanding games and creative workloads. Combines performance with portability.',
        price: 1999,
        discount: 0.4,
        purchasedCount: 267,
        imgSrc: '/images/computers/8.png',
    },
    {
        id: 9,
        categoryId: 1,
        name: 'Galaxy Flex Pro',
        type: '2-in-1 Laptop',
        description: 'Versatile convertible laptop that easily switches between laptop and tablet modes. Great for productivity, creativity, and entertainment.',
        price: 1699,
        purchasedCount: 351,
        imgSrc: '/images/computers/9.png',
    },

];

const clothes: Product[] = [
    {
        id: 10,
        categoryId: 2,
        name: 'Midnight Glow Dress',
        type: 'Dress',
        description: 'Elegant dress crafted for comfort and style. Perfect for special occasions, evening events, or sophisticated everyday wear.',
        price: 129,
        discount: 0.2,
        purchasedCount: 156,
        imgSrc: '/images/clothes/10.png',
    },
    {
        id: 11,
        categoryId: 2,
        name: 'Crystal Silk Dress',
        type: 'Dress',
        description: 'Elegant dress crafted for comfort and style. Perfect for special occasions, evening events, or sophisticated everyday wear.',
        price: 139,
        discount: 0.15,
        purchasedCount: 128,
        imgSrc: '/images/clothes/11.png',
    },
    {
        id: 12,
        categoryId: 2,
        name: 'Velvet Star Dress',
        type: 'Dress',
        description: 'Elegant dress crafted for comfort and style. Perfect for special occasions, evening events, or sophisticated everyday wear.',
        price: 149,
        discount: 0.1,
        purchasedCount: 97,
        imgSrc: '/images/clothes/12.png',
    },
    {
        id: 13,
        categoryId: 2,
        name: 'Moonlight Elegance Dress',
        type: 'Dress',
        description: 'Elegant dress crafted for comfort and style. Perfect for special occasions, evening events, or sophisticated everyday wear.',
        price: 159,
        discount: 0.25,
        purchasedCount: 203,
        imgSrc: '/images/clothes/13.png',
    },
    {
        id: 14,
        categoryId: 2,
        name: 'Noir Charm Dress',
        type: 'Dress',
        description: 'Elegant dress crafted for comfort and style. Perfect for special occasions, evening events, or sophisticated everyday wear.',
        price: 119,
        discount: 0.2,
        purchasedCount: 141,
        imgSrc: '/images/clothes/14.png',
    },
    {
        id: 15,
        categoryId: 2,
        name: 'Aurora Satin Dress',
        type: 'Dress',
        description: 'Elegant dress crafted for comfort and style. Perfect for special occasions, evening events, or sophisticated everyday wear.',
        price: 169,
        discount: 0.15,
        purchasedCount: 89,
        imgSrc: '/images/clothes/15.png',
    },
    {
        id: 16,
        categoryId: 2,
        name: 'Twilight Luxe Dress',
        type: 'Dress',
        description: 'Elegant dress crafted for comfort and style. Perfect for special occasions, evening events, or sophisticated everyday wear.',
        price: 149,
        discount: 0.3,
        purchasedCount: 174,
        imgSrc: '/images/clothes/16.png',
    },
    {
        id: 17,
        categoryId: 2,
        name: 'Diamond Night Dress',
        type: 'Dress',
        description: 'Elegant dress crafted for comfort and style. Perfect for special occasions, evening events, or sophisticated everyday wear.',
        price: 179,
        discount: 0.1,
        purchasedCount: 65,
        imgSrc: '/images/clothes/17.png',
    },
    {
        id: 18,
        categoryId: 2,
        name: 'Urban Classic Suit',
        type: 'Suit',
        description: 'Modern tailored suit made from quality materials for a refined appearance. Ideal for business meetings, formal events, and celebrations.',
        price: 189,
        discount: 0.15,
        purchasedCount: 203,
        imgSrc: '/images/clothes/18.png',
    },
    {
        id:19,
        categoryId: 2,
        name: 'Royal Navy Suit',
        type: 'Suit',
        description: 'Modern tailored suit made from quality materials for a refined appearance. Ideal for business meetings, formal events, and celebrations.',
        price: 249,
        discount: 0.1,
        purchasedCount: 142,
        imgSrc: '/images/clothes/19.png',
    },
    {
        id: 20,
        categoryId: 2,
        name: 'Executive Black Suit',
        type: 'Suit',
        description: 'Modern tailored suit made from quality materials for a refined appearance. Ideal for business meetings, formal events, and celebrations.',
        price: 279,
        discount: 0.2,
        purchasedCount: 98,
        imgSrc: '/images/clothes/20.png',
    },
    {
        id: 21,
        categoryId: 2,
        name: 'Modern Grey Suit',
        type: 'Suit',
        description: 'Modern tailored suit made from quality materials for a refined appearance. Ideal for business meetings, formal events, and celebrations.',
        price: 219,
        discount: 0.12,
        purchasedCount: 175,
        imgSrc: '/images/clothes/21.png',
    },
    {
        id: 22,
        categoryId: 2,
        name: 'Prestige Charcoal Suit',
        type: 'Suit',
        description: 'Modern tailored suit made from quality materials for a refined appearance. Ideal for business meetings, formal events, and celebrations.',
        price: 299,
        discount: 0.18,
        purchasedCount: 87,
        imgSrc: '/images/clothes/22.png',
    },
    {
        id: 23,
        categoryId: 2,
        name: 'Elegant Beige Suit',
        type: 'Suit',
        description: 'Modern tailored suit made from quality materials for a refined appearance. Ideal for business meetings, formal events, and celebrations.',
        price: 229,
        discount: 0.14,
        purchasedCount: 134,
        imgSrc: '/images/clothes/23.png',
    },
];

const shoes: Product[] = [
    {
        id: 24,
        categoryId: 3,
        name: 'Nike Air Max 270',
        type: 'Sneakers',
        description: 'Comfortable sneakers featuring responsive cushioning and durable construction. Suitable for everyday wear, walking, and active lifestyles.',
        price: 129,
        discount: 0.2,
        purchasedCount: 156,
        imgSrc: '/images/shoes/24.png',
    },
    {
        id: 25,
        categoryId: 3,
        name: 'Nike ZoomX Invincible',
        type: 'Sneakers',
        description: 'Comfortable sneakers featuring responsive cushioning and durable construction. Suitable for everyday wear, walking, and active lifestyles.',
        price: 179,
        discount: 0.15,
        purchasedCount: 243,
        imgSrc: '/images/shoes/25.png',
    },
    {
        id: 26,
        categoryId: 3,
        name: 'Adidas Ultraboost 5',
        type: 'Sneakers',
        description: 'Comfortable sneakers featuring responsive cushioning and durable construction. Suitable for everyday wear, walking, and active lifestyles.',
        price: 189,
        discount: 0.25,
        purchasedCount: 317,
        imgSrc: '/images/shoes/26.png',
    },
    {
        id: 27,
        categoryId: 3,
        name: 'Puma Velocity Nitro',
        type: 'Sneakers',
        description: 'Comfortable sneakers featuring responsive cushioning and durable construction. Suitable for everyday wear, walking, and active lifestyles.',
        price: 149,
        purchasedCount: 84,
        imgSrc: '/images/shoes/27.png',
    },
    {
        id: 28,
        categoryId: 3,
        name: 'New Balance 9060',
        type: 'Sneakers',
        description: 'Comfortable sneakers featuring responsive cushioning and durable construction. Suitable for everyday wear, walking, and active lifestyles.',
        price: 169,
        discount: 0.3,
        purchasedCount: 201,
        imgSrc: '/images/shoes/28.png',
    },
    {
        id: 29,
        categoryId: 3,
        name: 'Asics Gel-Kayano 31',
        type: 'Sneakers',
        description: 'Comfortable sneakers featuring responsive cushioning and durable construction. Suitable for everyday wear, walking, and active lifestyles.',
        price: 199,
        discount: 0.2,
        purchasedCount: 128,
        imgSrc: '/images/shoes/29.png',
    },
    {
        id: 30,
        categoryId: 3,
        name: 'Nike Pegasus 41',
        type: 'Sneakers',
        description: 'Comfortable sneakers featuring responsive cushioning and durable construction. Suitable for everyday wear, walking, and active lifestyles.',
        price: 139,
        discount: 0.15,
        purchasedCount: 412,
        imgSrc: '/images/shoes/30.png',
    },
    {
        id: 31,
        categoryId: 3,
        name: 'Adidas Adizero Boston',
        type: 'Sneakers',
        description: 'Comfortable sneakers featuring responsive cushioning and durable construction. Suitable for everyday wear, walking, and active lifestyles.',
        price: 159,
        purchasedCount: 178,
        imgSrc: '/images/shoes/31.png',
    },
    {
        id: 32,
        categoryId: 3,
        name: 'Reebok Floatride Energy',
        type: 'Sneakers',
        description: 'Comfortable sneakers featuring responsive cushioning and durable construction. Suitable for everyday wear, walking, and active lifestyles.',
        price: 119,
        discount: 0.25,
        purchasedCount: 92,
        imgSrc: '/images/shoes/32.png',
    },
    {
        id: 33,
        categoryId: 3,
        name: 'Under Armour HOVR Phantom',
        type: 'Sneakers',
        description: 'Comfortable sneakers featuring responsive cushioning and durable construction. Suitable for everyday wear, walking, and active lifestyles.',
        price: 149,
        discount: 0.2,
        purchasedCount: 135,
        imgSrc: '/images/shoes/33.png',
    },
    {
        id: 34,
        categoryId: 3,
        name: 'Saucony Endorphin Speed',
        type: 'Sneakers',
        description: 'Comfortable sneakers featuring responsive cushioning and durable construction. Suitable for everyday wear, walking, and active lifestyles.',
        price: 189,
        discount: 0.4,
        purchasedCount: 267,
        imgSrc: '/images/shoes/34.png',
    },
    {
        id: 35,
        categoryId: 3,
        name: 'Hoka Clifton 10',
        type: 'Sneakers',
        description: 'Comfortable sneakers featuring responsive cushioning and durable construction. Suitable for everyday wear, walking, and active lifestyles.',
        price: 174,
        purchasedCount: 351,
        imgSrc: '/images/shoes/35.png',
    },
];

const furnitures: Product[] = [
    {
        id: 36,
        categoryId: 4,
        name: 'Nordic Comfort Chair',
        type: 'Furniture',
        description: 'Stylish and durable furniture piece designed to complement modern interiors. Combines functionality, comfort, and long-lasting quality.',
        price: 249,
        discount: 0.15,
        purchasedCount: 87,
        imgSrc: '/images/furnitures/36.png',
    },
    {
        id: 37,
        categoryId: 4,
        name: 'Emerald Velvet Chair',
        type: 'Furniture',
        description: 'Stylish and durable furniture piece designed to complement modern interiors. Combines functionality, comfort, and long-lasting quality.',
        price: 279,
        discount: 0.2,
        purchasedCount: 64,
        imgSrc: '/images/furnitures/37.png',
    },
    {
        id: 38,
        categoryId: 4,
        name: 'Graphite Lounge Chair',
        type: 'Furniture',
        description: 'Stylish and durable furniture piece designed to complement modern interiors. Combines functionality, comfort, and long-lasting quality.',
        price: 259,
        purchasedCount: 51,
        imgSrc: '/images/furnitures/38.png',
    },
    {
        id: 39,
        categoryId: 4,
        name: 'Ivory Classic Chair',
        type: 'Furniture',
        description: 'Stylish and durable furniture piece designed to complement modern interiors. Combines functionality, comfort, and long-lasting quality.',
        price: 239,
        discount: 0.1,
        purchasedCount: 73,
        imgSrc: '/images/furnitures/39.png',
    },
    {
        id: 40,
        categoryId: 4,
        name: 'Scandinavian Oak Chair',
        type: 'Furniture',
        description: 'Stylish and durable furniture piece designed to complement modern interiors. Combines functionality, comfort, and long-lasting quality.',
        price: 269,
        discount: 0.25,
        purchasedCount: 92,
        imgSrc: '/images/furnitures/40.png',
    },
    {
        id: 41,
        categoryId: 4,
        name: 'Executive Leather Chair',
        type: 'Furniture',
        description: 'Stylish and durable furniture piece designed to complement modern interiors. Combines functionality, comfort, and long-lasting quality.',
        price: 399,
        purchasedCount: 38,
        imgSrc: '/images/furnitures/41.png',
    },
    {
        id: 42,
        categoryId: 4,
        name: 'TimberCraft Coffee Table',
        type: 'Furniture',
        description: 'Stylish and durable furniture piece designed to complement modern interiors. Combines functionality, comfort, and long-lasting quality.',
        price: 349,
        discount: 0.2,
        purchasedCount: 114,
        imgSrc: '/images/furnitures/42.png',
    },
    {
        id: 43,
        categoryId: 4,
        name: 'Walnut Round Table',
        type: 'Furniture',
        description: 'Stylish and durable furniture piece designed to complement modern interiors. Combines functionality, comfort, and long-lasting quality.',
        price: 449,
        discount: 0.15,
        purchasedCount: 96,
        imgSrc: '/images/furnitures/43.png',
    },
    {
        id: 44,
        categoryId: 4,
        name: 'Marble Aura Table',
        type: 'Furniture',
        description: 'Stylish and durable furniture piece designed to complement modern interiors. Combines functionality, comfort, and long-lasting quality.',
        price: 699,
        discount: 0.3,
        purchasedCount: 47,
        imgSrc: '/images/furnitures/44.png',
    },
    {
        id: 45,
        categoryId: 4,
        name: 'Midnight Executive Desk',
        type: 'Furniture',
        description: 'Stylish and durable furniture piece designed to complement modern interiors. Combines functionality, comfort, and long-lasting quality.',
        price: 799,
        purchasedCount: 29,
        imgSrc: '/images/furnitures/45.png',
    },
    {
        id: 46,
        categoryId: 4,
        name: 'Minimalist Work Desk',
        type: 'Furniture',
        description: 'Stylish and durable furniture piece designed to complement modern interiors. Combines functionality, comfort, and long-lasting quality.',
        price: 429,
        discount: 0.1,
        purchasedCount: 134,
        imgSrc: '/images/furnitures/46.png',
    },
    {
        id: 47,
        categoryId: 4,
        name: 'Shadow Office Desk',
        type: 'Furniture',
        description: 'Stylish and durable furniture piece designed to complement modern interiors. Combines functionality, comfort, and long-lasting quality.',
        price: 549,
        discount: 0.2,
        purchasedCount: 88,
        imgSrc: '/images/furnitures/47.png',
    },
    {
        id: 48,
        categoryId: 4,
        name: 'Cloud Comfort Sofa',
        type: 'Furniture',
        description: 'Stylish and durable furniture piece designed to complement modern interiors. Combines functionality, comfort, and long-lasting quality.',
        price: 899,
        discount: 0.3,
        purchasedCount: 174,
        imgSrc: '/images/furnitures/48.png',
    },
    {
        id: 49,
        categoryId: 4,
        name: 'Vintage Walnut Cabinet',
        type: 'Furniture',
        description: 'Stylish and durable furniture piece designed to complement modern interiors. Combines functionality, comfort, and long-lasting quality.',
        price: 589,
        discount: 0.25,
        purchasedCount: 42,
        imgSrc: '/images/furnitures/49.png',
    },
    {
        id: 50,
        categoryId: 4,
        name: 'Nordic Storage Console',
        type: 'Furniture',
        description: 'Stylish and durable furniture piece designed to complement modern interiors. Combines functionality, comfort, and long-lasting quality.',
        price: 479,
        purchasedCount: 97,
        imgSrc: '/images/furnitures/50.png',
    },
];

const cosmetics: Product[] = [
    {
        id: 51,
        categoryId: 5,
        name: 'Neon Silk Shampoo',
        type: 'Cosmetics',
        description: 'Premium personal care product formulated to support healthy skin and hair. Designed for effective daily use and lasting freshness.',
        price: 24,
        discount: 0.2,
        purchasedCount: 187,
        imgSrc: '/images/cosmetics/51.png',
    },
    {
        id: 52,
        categoryId: 5,
        name: 'Galaxy Glow Body Wash',
        type: 'Cosmetics',
        description: 'Premium personal care product formulated to support healthy skin and hair. Designed for effective daily use and lasting freshness.',
        price: 19,
        discount: 0.15,
        purchasedCount: 243,
        imgSrc: '/images/cosmetics/52.png',
    },
    {
        id: 53,
        categoryId: 5,
        name: 'Luna Repair Shampoo',
        type: 'Cosmetics',
        description: 'Premium personal care product formulated to support healthy skin and hair. Designed for effective daily use and lasting freshness.',
        price: 22,
        purchasedCount: 156,
        imgSrc: '/images/cosmetics/53.png',
    },
    {
        id: 54,
        categoryId: 5,
        name: 'Nova Hydration Foam',
        type: 'Cosmetics',
        description: 'Premium personal care product formulated to support healthy skin and hair. Designed for effective daily use and lasting freshness.',
        price: 29,
        discount: 0.25,
        purchasedCount: 118,
        imgSrc: '/images/cosmetics/54.png',
    },
    {
        id: 55,
        categoryId: 5,
        name: 'Cosmic Shine Conditioner',
        type: 'Cosmetics',
        description: 'Premium personal care product formulated to support healthy skin and hair. Designed for effective daily use and lasting freshness.',
        price: 21,
        discount: 0.1,
        purchasedCount: 174,
        imgSrc: '/images/cosmetics/55.png',
    },
    {
        id: 56,
        categoryId: 5,
        name: 'Lavender Fresh Lotion',
        type: 'Cosmetics',
        description: 'Premium personal care product formulated to support healthy skin and hair. Designed for effective daily use and lasting freshness.',
        price: 18,
        purchasedCount: 201,
        imgSrc: '/images/cosmetics/56.png',
    },
    {
        id: 57,
        categoryId: 5,
        name: 'Spice Sands Body Cleanser',
        type: 'Cosmetics',
        description: 'Premium personal care product formulated to support healthy skin and hair. Designed for effective daily use and lasting freshness.',
        price: 23,
        discount: 0.2,
        purchasedCount: 92,
        imgSrc: '/images/cosmetics/57.png',
    },
    {
        id: 58,
        categoryId: 5,
        name: 'Midnight Galaxy Shampoo',
        type: 'Cosmetics',
        description: 'Premium personal care product formulated to support healthy skin and hair. Designed for effective daily use and lasting freshness.',
        price: 26,
        discount: 0.3,
        purchasedCount: 267,
        imgSrc: '/images/cosmetics/58.png',
    },
    {
        id: 59,
        categoryId: 5,
        name: 'Lavender Dream Set',
        type: 'Cosmetics',
        description: 'Premium personal care product formulated to support healthy skin and hair. Designed for effective daily use and lasting freshness.',
        price: 34,
        purchasedCount: 135,
        imgSrc: '/images/cosmetics/59.png',
    },
    {
        id: 60,
        categoryId: 5,
        name: 'Botanica Essence Soap',
        type: 'Cosmetics',
        description: 'Premium personal care product formulated to support healthy skin and hair. Designed for effective daily use and lasting freshness.',
        price: 12,
        discount: 0.15,
        purchasedCount: 321,
        imgSrc: '/images/cosmetics/60.png',
    },
    {
        id: 61,
        categoryId: 5,
        name: 'Pure Bloom Soap Bar',
        type: 'Cosmetics',
        description: 'Premium personal care product formulated to support healthy skin and hair. Designed for effective daily use and lasting freshness.',
        price: 9,
        discount: 0.25,
        purchasedCount: 412,
        imgSrc: '/images/cosmetics/61.png',
    },
    {
        id: 62,
        categoryId: 5,
        name: 'Aurora Mist Shampoo',
        type: 'Cosmetics',
        description: 'Premium personal care product formulated to support healthy skin and hair. Designed for effective daily use and lasting freshness.',
        price: 27,
        discount: 0.2,
        purchasedCount: 158,
        imgSrc: '/images/cosmetics/62.png',
    }
];

const dishes: Product[] = [
    {
        id: 63,
        categoryId: 6,
        name: 'Midnight Ceramic Set',
        type: 'Dishes',
        description: 'Elegant kitchen and dining set crafted from durable materials. Perfect for everyday meals and special gatherings.',
        price: 89,
        discount: 0.2,
        purchasedCount: 143,
        imgSrc: '/images/dishes/63.png',
    },
    {
        id: 64,
        categoryId: 6,
        name: 'Royal Gold Tea Collection',
        type: 'Dishes',
        description: 'Elegant kitchen and dining set crafted from durable materials. Perfect for everyday meals and special gatherings.',
        price: 119,
        discount: 0.15,
        purchasedCount: 92,
        imgSrc: '/images/dishes/64.png',
    },
    {
        id: 65,
        categoryId: 6,
        name: 'Nordic Stone Bowl Set',
        type: 'Dishes',
        description: 'Elegant kitchen and dining set crafted from durable materials. Perfect for everyday meals and special gatherings.',
        price: 74,
        purchasedCount: 187,
        imgSrc: '/images/dishes/65.png',
    },
    {
        id: 66,
        categoryId: 6,
        name: 'Ivory Classic Dinnerware',
        type: 'Dishes',
        description: 'Elegant kitchen and dining set crafted from durable materials. Perfect for everyday meals and special gatherings.',
        price: 99,
        discount: 0.25,
        purchasedCount: 215,
        imgSrc: '/images/dishes/66.png',
    },
    {
        id: 67,
        categoryId: 6,
        name: 'Pearl Essence Plate Set',
        type: 'Dishes',
        description: 'Elegant kitchen and dining set crafted from durable materials. Perfect for everyday meals and special gatherings.',
        price: 109,
        discount: 0.1,
        purchasedCount: 168,
        imgSrc: '/images/dishes/67.png',
    },
    {
        id: 68,
        categoryId: 6,
        name: 'Scandinavian Table Collection',
        type: 'Dishes',
        description: 'Elegant kitchen and dining set crafted from durable materials. Perfect for everyday meals and special gatherings.',
        price: 94,
        purchasedCount: 131,
        imgSrc: '/images/dishes/68.png',
    },
    {
        id: 69,
        categoryId: 6,
        name: 'Minimal White Kitchen Set',
        type: 'Dishes',
        description: 'Elegant kitchen and dining set crafted from durable materials. Perfect for everyday meals and special gatherings.',
        price: 79,
        discount: 0.3,
        purchasedCount: 247,
        imgSrc: '/images/dishes/69.png',
    },
    {
        id: 70,
        categoryId: 6,
        name: 'Morning Coffee Ritual Set',
        type: 'Dishes',
        description: 'Elegant kitchen and dining set crafted from durable materials. Perfect for everyday meals and special gatherings.',
        price: 49,
        discount: 0.2,
        purchasedCount: 324,
        imgSrc: '/images/dishes/70.png',
    },
];

const sportsEquipment: Product[] = [
    {
        id: 71,
        categoryId: 7,
        name: 'Arctic Pro Skis',
        type: 'Skis',
        description: 'Performance skis engineered for stability, control, and confidence on snowy slopes. Suitable for recreational and advanced riders.',
        price: 549,
        discount: 0.2,
        purchasedCount: 87,
        imgSrc: '/images/sports-equipment/71.png',
    },
    {
        id: 72,
        categoryId: 7,
        name: 'Galaxy Rider Skis',
        type: 'Skis',
        description: 'Performance skis engineered for stability, control, and confidence on snowy slopes. Suitable for recreational and advanced riders.',
        price: 629,
        discount: 0.15,
        purchasedCount: 62,
        imgSrc: '/images/sports-equipment/72.png',
    },
    {
        id: 73,
        categoryId: 7,
        name: 'Titan Boxing Bag',
        type: 'Punching Bag',
        description: 'Durable punching bag built to withstand intense training sessions. Helps improve strength, endurance, and technique.',
        price: 219,
        discount: 0.25,
        purchasedCount: 201,
        imgSrc: '/images/sports-equipment/73.png',
    },
    {
        id: 74,
        categoryId: 7,
        name: 'Nebula Snowboard',
        type: 'Snowboard',
        description: 'Versatile snowboard offering excellent balance, control, and responsiveness. Designed for enjoyable rides in various snow conditions.',
        price: 449,
        discount: 0.2,
        purchasedCount: 95,
        imgSrc: '/images/sports-equipment/74.png',
    },
    {
        id: 75,
        categoryId: 7,
        name: 'Shadow Edge Snowboard',
        type: 'Snowboard',
        description: 'Versatile snowboard offering excellent balance, control, and responsiveness. Designed for enjoyable rides in various snow conditions.',
        price: 479,
        purchasedCount: 73,
        imgSrc: '/images/sports-equipment/75.png',
    },
    {
        id: 76,
        categoryId: 7,
        name: 'Speed Reflex Trainer',
        type: 'Reflex Trainer',
        description: 'Training equipment designed to improve reaction time, coordination, and accuracy. Ideal for boxing and fitness workouts.',
        price: 149,
        discount: 0.1,
        purchasedCount: 182,
        imgSrc: '/images/sports-equipment/76.png',
    },
    {
        id: 77,
        categoryId: 7,
        name: 'Elite Sparring Gloves',
        type: 'Boxing Gloves',
        description: 'Protective boxing gloves offering comfort, support, and impact absorption. Suitable for sparring, bag work, and training.',
        price: 79,
        discount: 0.15,
        purchasedCount: 267,
        imgSrc: '/images/sports-equipment/77.png',
    },
    {
        id: 78,
        categoryId: 7,
        name: 'Frost Boxing Boots',
        type: 'Boxing Boots',
        description: 'Lightweight boxing boots designed for stability, agility, and footwork. Provide excellent grip and ring performance.',
        price: 119,
        purchasedCount: 138,
        imgSrc: '/images/sports-equipment/78.png',
    },
    {
        id: 79,
        categoryId: 7,
        name: 'Crimson Strike Gloves',
        type: 'Boxing Gloves',
        description: 'Protective boxing gloves offering comfort, support, and impact absorption. Suitable for sparring, bag work, and training.',
        price: 89,
        discount: 0.2,
        purchasedCount: 194,
        imgSrc: '/images/sports-equipment/79.png',
    },
    {
        id: 80,
        categoryId: 7,
        name: 'Golden Champion Gloves',
        type: 'Boxing Gloves',
        description: 'Protective boxing gloves offering comfort, support, and impact absorption. Suitable for sparring, bag work, and training.',
        price: 99,
        purchasedCount: 121,
        imgSrc: '/images/sports-equipment/80.png',
    },
    {
        id: 81,
        categoryId: 7,
        name: 'Power Dumbbell Set',
        type: 'Dumbbells',
        description: 'Durable dumbbell set suitable for strength training and full-body workouts. Great for building muscle and improving fitness.',
        price: 179,
        discount: 0.25,
        purchasedCount: 312,
        imgSrc: '/images/sports-equipment/81.png',
    },
    {
        id: 82,
        categoryId: 7,
        name: 'Velocity Focus Pads',
        type: 'Focus Pads',
        description: 'Professional focus pads designed for speed, precision, and striking drills. Perfect for boxing and martial arts training.',
        price: 69,
        purchasedCount: 143,
        imgSrc: '/images/sports-equipment/82.png',
    },
    {
        id: 83,
        categoryId: 7,
        name: 'Combat Training Gloves',
        type: 'Training Gloves',
        description: 'Comfortable training gloves built for repeated workouts and skill development. Provide protection and reliable performance.',
        price: 59,
        discount: 0.3,
        purchasedCount: 227,
        imgSrc: '/images/sports-equipment/83.png',
    },
    {
        id: 84,
        categoryId: 7,
        name: 'RunMaster Treadmill',
        type: 'Treadmill',
        description: 'High-quality treadmill designed for convenient indoor cardio workouts. Features a stable platform and smooth running experience.',
        price: 899,
        discount: 0.15,
        purchasedCount: 48,
        imgSrc: '/images/sports-equipment/84.png',
    },
    {
        id: 85,
        categoryId: 7,
        name: 'Iron Beast Bench Set',
        type: 'Weight Bench',
        description: 'Heavy-duty weight bench suitable for strength training and home gym setups. Built for stability and versatility.',
        price: 649,
        purchasedCount: 77,
        imgSrc: '/images/sports-equipment/85.png',
    },
    {
        id: 86,
        categoryId: 7,
        name: 'Arctic Pro Skis',
        type: 'Skis',
        description: 'Performance skis engineered for stability, control, and confidence on snowy slopes. Suitable for recreational and advanced riders.',
        price: 679,
        discount: 0.2,
        purchasedCount: 187,
        imgSrc: '/images/sports-equipment/86.png',
    },
    {
        id: 87,
        categoryId: 7,
        name: 'Galaxy Rider Skis',
        type: 'Skis',
        description: 'Performance skis engineered for stability, control, and confidence on snowy slopes. Suitable for recreational and advanced riders.',
        price: 699,
        discount: 0.25,
        purchasedCount: 32,
        imgSrc: '/images/sports-equipment/87.png',
    },
    {
        id: 88,
        categoryId: 7,
        name: 'Titan Boxing Bag',
        type: 'Punching Bag',
        description: 'Durable punching bag built to withstand intense training sessions. Helps improve strength, endurance, and technique.',
        price: 269,
        discount: 0.35,
        purchasedCount: 101,
        imgSrc: '/images/sports-equipment/88.png',
    },
    {
        id: 89,
        categoryId: 7,
        name: 'Nebula Snowboard',
        type: 'Snowboard',
        description: 'Versatile snowboard offering excellent balance, control, and responsiveness. Designed for enjoyable rides in various snow conditions.',
        price: 449,
        discount: 0.3,
        purchasedCount: 95,
        imgSrc: '/images/sports-equipment/89.png',
    },
    {
        id: 90,
        categoryId: 7,
        name: 'Shadow Edge Snowboard',
        type: 'Snowboard',
        description: 'Versatile snowboard offering excellent balance, control, and responsiveness. Designed for enjoyable rides in various snow conditions.',
        price: 569,
        purchasedCount: 43,
        imgSrc: '/images/sports-equipment/90.png',
    },
    {
        id: 91,
        categoryId: 7,
        name: 'Speed Reflex Trainer',
        type: 'Reflex Trainer',
        description: 'Training equipment designed to improve reaction time, coordination, and accuracy. Ideal for boxing and fitness workouts.',
        price: 169,
        discount: 0.2,
        purchasedCount: 182,
        imgSrc: '/images/sports-equipment/91.png',
    },
    {
        id: 92,
        categoryId: 7,
        name: 'Elite Sparring Gloves',
        type: 'Boxing Gloves',
        description: 'Protective boxing gloves offering comfort, support, and impact absorption. Suitable for sparring, bag work, and training.',
        price: 99,
        discount: 0.25,
        purchasedCount: 167,
        imgSrc: '/images/sports-equipment/92.png',
    },
    {
        id: 93,
        categoryId: 7,
        name: 'Frost Boxing Boots',
        type: 'Boxing Boots',
        description: 'Lightweight boxing boots designed for stability, agility, and footwork. Provide excellent grip and ring performance.',
        price: 219,
        purchasedCount: 148,
        imgSrc: '/images/sports-equipment/78.png',
    },
    {
        id: 94,
        categoryId: 7,
        name: 'Crimson Strike Gloves',
        type: 'Boxing Gloves',
        description: 'Protective boxing gloves offering comfort, support, and impact absorption. Suitable for sparring, bag work, and training.',
        price: 99,
        discount: 0.3,
        purchasedCount: 154,
        imgSrc: '/images/sports-equipment/94.png',
    },
    {
        id: 95,
        categoryId: 7,
        name: 'Golden Champion Gloves',
        type: 'Boxing Gloves',
        description: 'Protective boxing gloves offering comfort, support, and impact absorption. Suitable for sparring, bag work, and training.',
        price: 59,
        purchasedCount: 221,
        imgSrc: '/images/sports-equipment/95.png',
    },
    {
        id: 96,
        categoryId: 7,
        name: 'Power Dumbbell Set',
        type: 'Dumbbells',
        description: 'Durable dumbbell set suitable for strength training and full-body workouts. Great for building muscle and improving fitness.',
        price: 189,
        discount: 0.15,
        purchasedCount: 212,
        imgSrc: '/images/sports-equipment/96.png',
    },
    {
        id: 97,
        categoryId: 7,
        name: 'Velocity Focus Pads',
        type: 'Focus Pads',
        description: 'Professional focus pads designed for speed, precision, and striking drills. Perfect for boxing and martial arts training.',
        price: 49,
        purchasedCount: 123,
        imgSrc: '/images/sports-equipment/97.png',
    },
    {
        id: 98,
        categoryId: 7,
        name: 'Combat Training Gloves',
        type: 'Training Gloves',
        description: 'Comfortable training gloves built for repeated workouts and skill development. Provide protection and reliable performance.',
        price: 49,
        discount: 0.3,
        purchasedCount: 127,
        imgSrc: '/images/sports-equipment/98.png',
    },
    {
        id: 99,
        categoryId: 7,
        name: 'RunMaster Treadmill',
        type: 'Treadmill',
        description: 'High-quality treadmill designed for convenient indoor cardio workouts. Features a stable platform and smooth running experience.',
        price: 799,
        discount: 0.25,
        purchasedCount: 48,
        imgSrc: '/images/sports-equipment/99.png',
    },
    {
        id: 100,
        categoryId: 7,
        name: 'Iron Beast Bench Set',
        type: 'Weight Bench',
        description: 'Heavy-duty weight bench suitable for strength training and home gym setups. Built for stability and versatility.',
        price: 549,
        purchasedCount: 57,
        imgSrc: '/images/sports-equipment/100.png',
    },

];


export const products: Product[][] = [];
products[1] = computers;
products[2] = clothes;
products[3] = shoes;
products[4] = furnitures;
products[5] = cosmetics;
products[6] = dishes;
products[7] = sportsEquipment;

