import type {Product} from "@/entities/products/model/type.ts";

export const trendingItems: Product[] = [
    {
        id: 1,
        categoryId: 1,
        name: 'Quantum Core X1',
        type: 'Gaming PC',
        price: 1899,
        discount: 0.2,
        purchasedCount: 156,
        imgSrc: '/images/computers/1.png',
    },
    {
        id: 6,
        categoryId: 1,
        name: 'Infinity View One',
        type: 'All-in-One PC',
        price: 1399,
        discount: 0.2,
        purchasedCount: 128,
        imgSrc: '/images/computers/6.png',
    },
    {
        id: 8,
        categoryId: 1,
        name: 'Vortex Ultra X',
        type: 'Gaming Laptop',
        price: 1999,
        discount: 0.4,
        purchasedCount: 267,
        imgSrc: '/images/computers/8.png',
    },
    {
        id: 10,
        categoryId: 2,
        name: 'Midnight Glow Dress',
        type: 'Dress',
        price: 129,
        discount: 0.2,
        purchasedCount: 156,
        imgSrc: '/images/clothes/10.png',
    },
    {
        id: 16,
        categoryId: 2,
        name: 'Twilight Luxe Dress',
        type: 'Dress',
        price: 149,
        discount: 0.3,
        purchasedCount: 174,
        imgSrc: '/images/clothes/16.png',
    },
    {
        id: 22,
        categoryId: 2,
        name: 'Prestige Charcoal Suit',
        type: 'Suit',
        price: 299,
        discount: 0.18,
        purchasedCount: 87,
        imgSrc: '/images/clothes/22.png',
    },
    {
        id: 28,
        categoryId: 3,
        name: 'New Balance 9060',
        type: 'Sneakers',
        price: 169,
        discount: 0.3,
        purchasedCount: 201,
        imgSrc: '/images/shoes/28.png',
    },
    {
        id: 33,
        categoryId: 3,
        name: 'Under Armour HOVR Phantom',
        type: 'Sneakers',
        price: 149,
        discount: 0.2,
        purchasedCount: 135,
        imgSrc: '/images/shoes/33.png',
    },
    {
        id: 35,
        categoryId: 3,
        name: 'Hoka Clifton 10',
        type: 'Sneakers',
        price: 174,
        purchasedCount: 351,
        imgSrc: '/images/shoes/35.png',
    },
    {
        id: 41,
        categoryId: 4,
        name: 'Executive Leather Chair',
        type: 'Furniture',
        price: 399,
        purchasedCount: 38,
        imgSrc: '/images/furnitures/41.png',
    },
    {
        id: 44,
        categoryId: 4,
        name: 'Marble Aura Table',
        type: 'Furniture',
        price: 699,
        discount: 0.3,
        purchasedCount: 47,
        imgSrc: '/images/furnitures/44.png',
    },
    {
        id: 48,
        categoryId: 4,
        name: 'Cloud Comfort Sofa',
        type: 'Furniture',
        price: 899,
        discount: 0.3,
        purchasedCount: 174,
        imgSrc: '/images/furnitures/48.png',
    },
    {
        id: 53,
        categoryId: 5,
        name: 'Luna Repair Shampoo',
        type: 'Cosmetics',
        price: 22,
        purchasedCount: 156,
        imgSrc: '/images/cosmetics/53.png',
    },
    {
        id: 57,
        categoryId: 5,
        name: 'Spice Sands Body Cleanser',
        type: 'Cosmetics',
        price: 23,
        discount: 0.2,
        purchasedCount: 92,
        imgSrc: '/images/cosmetics/57.png',
    },
    {
        id: 59,
        categoryId: 5,
        name: 'Lavender Dream Set',
        type: 'Cosmetics',
        price: 34,
        purchasedCount: 135,
        imgSrc: '/images/cosmetics/59.png',
    },
    {
        id: 60,
        categoryId: 5,
        name: 'Botanica Essence Soap',
        type: 'Cosmetics',
        price: 12,
        discount: 0.15,
        purchasedCount: 321,
        imgSrc: '/images/cosmetics/60.png',
    },
    {
        id: 63,
        categoryId: 6,
        name: 'Midnight Ceramic Set',
        type: 'Dishes',
        price: 89,
        discount: 0.2,
        purchasedCount: 143,
        imgSrc: '/images/dishes/63.png',
    },
    {
        id: 65,
        categoryId: 6,
        name: 'Nordic Stone Bowl Set',
        type: 'Dishes',
        price: 74,
        purchasedCount: 187,
        imgSrc: '/images/dishes/65.png',
    },
    {
        id: 72,
        categoryId: 7,
        name: 'Galaxy Rider Skis',
        type: 'Skis',
        price: 629,
        discount: 0.15,
        purchasedCount: 62,
        imgSrc: '/images/sports-equipment/72.png',
    },
    {
        id: 74,
        categoryId: 7,
        name: 'Nebula Snowboard',
        type: 'Snowboard',
        price: 449,
        discount: 0.2,
        purchasedCount: 95,
        imgSrc: '/images/sports-equipment/74.png',
    },
    {
        id: 80,
        categoryId: 7,
        name: 'Golden Champion Gloves',
        type: 'Boxing Gloves',
        price: 99,
        purchasedCount: 121,
        imgSrc: '/images/sports-equipment/80.png',
    },
    {
        id: 84,
        categoryId: 7,
        name: 'RunMaster Treadmill',
        type: 'Treadmill',
        price: 899,
        discount: 0.15,
        purchasedCount: 48,
        imgSrc: '/images/sports-equipment/84.png',
    },
];

