import type {Product} from "@/entities/products/model/type.ts";

export const trendingItems: Product[] = [
    {
        id: 1,
        name: 'Quantum Core X1',
        type: 'Gaming PC',
        price: 1899,
        discount: 0.2,
        purchasedCount: 156,
        imgSrc: '/images/computers/1.png',
    },
    {
        id: 6,
        name: 'Infinity View One',
        type: 'All-in-One PC',
        price: 1399,
        discount: 0.2,
        purchasedCount: 128,
        imgSrc: '/images/computers/6.png',
    },
    {
        id: 8,
        name: 'Vortex Ultra X',
        type: 'Gaming Laptop',
        price: 1999,
        discount: 0.4,
        purchasedCount: 267,
        imgSrc: '/images/computers/8.png',
    },
    {
        id: 10,
        name: 'Midnight Glow Dress',
        type: 'Dress',
        price: 129,
        discount: 0.2,
        purchasedCount: 156,
        imgSrc: '/images/clothes/10.png',
    },
    {
        id: 16,
        name: 'Twilight Luxe Dress',
        type: 'Dress',
        price: 149,
        discount: 0.3,
        purchasedCount: 174,
        imgSrc: '/images/clothes/16.png',
    },
    {
        id: 22,
        name: 'Prestige Charcoal Suit',
        type: 'Suit',
        price: 299,
        discount: 0.18,
        purchasedCount: 87,
        imgSrc: '/images/clothes/22.png',
    },
    {
        id: 28,
        name: 'New Balance 9060',
        type: 'Sneakers',
        price: 169,
        discount: 0.3,
        purchasedCount: 201,
        imgSrc: '/images/shoes/28.png',
    },
    {
        id: 33,
        name: 'Under Armour HOVR Phantom',
        type: 'Sneakers',
        price: 149,
        discount: 0.2,
        purchasedCount: 135,
        imgSrc: '/images/shoes/33.png',
    },
    {
        id: 35,
        name: 'Hoka Clifton 10',
        type: 'Sneakers',
        price: 174,
        purchasedCount: 351,
        imgSrc: '/images/shoes/35.png',
    },
    {
        id: 41,
        name: 'Executive Leather Chair',
        type: 'Furniture',
        price: 399,
        purchasedCount: 38,
        imgSrc: '/images/furnitures/41.png',
    },
    {
        id: 44,
        name: 'Marble Aura Table',
        type: 'Furniture',
        price: 699,
        discount: 0.3,
        purchasedCount: 47,
        imgSrc: '/images/furnitures/44.png',
    },
    {
        id: 48,
        name: 'Cloud Comfort Sofa',
        type: 'Furniture',
        price: 899,
        discount: 0.3,
        purchasedCount: 174,
        imgSrc: '/images/furnitures/48.png',
    },
];

